### ISSUE TITLE
Issue getting parameters to subfields

### ISSUE THREAD

**Issue by zeroSteiner** [dmendel/bindata#123]
I'm having an issue creating a new instance of a type when I set it's value to one where I have a parameter defined. Take the following three classes. My array `MemberValues` needs to get it's type information from a `type_map` that occurs somewhere in the binary stream. I have it defined as a mandatory parameter, and a class (`Container`) with a `MemberValues` field where the `type_map` can be resolved when parsing but needs to be explicitly defined when constructing.

In the following example, when `oc1` is initialized from an existing `Container` instance, the `type_map` parameter fails to resolve, resulting in an exception<sup>1</sup>. It seems like because `c1` is already defined, there shouldn't be an issue when creating the `OuterContainer`. I would think that `oc1` would then be `{:something=>{:member_values=>[0, 123]}}`.

```ruby
class MemberValues < BinData::Array
  endian :little
  mandatory_parameter    :type_map
  choice                 :my_field, selection: -> { eval_parameter(:type_map)[index] } do
    int32                'int32',  initial_value: 123
    string               'string', initial_value: 'abc'
  end
end

class Container < BinData::Record
  optional_parameter     :type_map_param
  member_values          :member_values, type_map: -> { type_map }
  
  #attr_reader :params
  #def assign(v, *args)
  #  @params.merge!(v.params) if v.is_a? self.class
  #  super(v, *args)
  #end
  
  def type_map
    puts 'in def type_map'
    eval_parameter(:type_map_param)
  end
end

class OuterContainer < BinData::Record
  container              :something
end

mv1 = MemberValues.new([0, 123], type_map: ['int32', 'int32'])
mv2 = MemberValues.new(['', 'abc'], type_map: ['string', 'string'])

c1 = Container.new({member_values: mv1}, type_map: ['int32', 'int32'])
c2 = Container.new({member_values: mv2}, type_map: ['string', 'string'])

puts "#{c1.member_values}, #{c2.member_values}"

oc1 = OuterContainer.new(something: c1)
oc2 = OuterContainer.new(something: c2)
```

One thing I tried was copying the parameters (you can see the code I left commented out) which technically fixed the creation of `oc1` however, if you compare `oc1` and `oc2`, you'll notice that their unique type maps are not being used (instead of `oc1` being `{:something=>{:member_values=>[0, 123]}}`, it's `{:something=>{:member_values=>["abc", "abc"]}}`). This appears to be due to the `@param.merge!` technique overriding the original with the second.

<sup>1</sup> Exception
```
NoMethodError: undefined method `[]' for nil:NilClass
(pry):3538:in `block in <class:MemberValues>'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/lazy.rb:33:in `instance_exec'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/lazy.rb:33:in `lazy_eval'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/base.rb:113:in `eval_parameter'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/choice.rb:81:in `selection'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/choice.rb:108:in `current_choice'
(eval):2:in `assign'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/array.rb:175:in `[]='
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/array.rb:131:in `block in insert'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/array.rb:130:in `each'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/array.rb:130:in `each_with_index'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/array.rb:130:in `insert'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/array.rb:117:in `concat'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/array.rb:86:in `assign'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/struct.rb:233:in `block in assign_fields'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/struct.rb:230:in `each'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/struct.rb:230:in `assign_fields'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/struct.rb:102:in `assign'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/struct.rb:233:in `block in assign_fields'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/struct.rb:230:in `each'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/struct.rb:230:in `assign_fields'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/struct.rb:102:in `assign'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/base.rb:85:in `initialize'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/bindata-2.4.7/lib/bindata/warnings.rb:21:in `initialize_with_warning'
(pry):3572:in `new'
(pry):3572:in `<main>'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `eval'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `evaluate_ruby'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/pry-0.12.2/lib/pry/pry_instance.rb:355:in `handle_line'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/pry-0.12.2/lib/pry/pry_instance.rb:274:in `block (2 levels) in eval'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `catch'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `block in eval'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `catch'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `eval'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/iruby-0.4.0/lib/iruby/backend.rb:66:in `eval'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/iruby-0.4.0/lib/iruby/backend.rb:12:in `eval'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/iruby-0.4.0/lib/iruby/kernel.rb:90:in `execute_request'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/iruby-0.4.0/lib/iruby/kernel.rb:49:in `dispatch'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/iruby-0.4.0/lib/iruby/kernel.rb:38:in `run'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/iruby-0.4.0/lib/iruby/command.rb:110:in `run_kernel'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/iruby-0.4.0/lib/iruby/command.rb:40:in `run'
/home/steiner/.rvm/gems/ruby-2.5.5/gems/iruby-0.4.0/bin/iruby:5:in `<top (required)>'
/home/steiner/.rvm/gems/ruby-2.5.5/bin/iruby:23:in `load'
/home/steiner/.rvm/gems/ruby-2.5.5/bin/iruby:23:in `<main>'
/home/steiner/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/home/steiner/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by dmendel** [comment]
BinData is declarative, rather than imperative. This requires that value assignment is pass by value, not pass by reference. 

Here is a simplified example of what you are attempting to do.
```ruby
str1 = BinData::String.new("abc", length: 10, trim_padding: true)
p str1.to_binary_s # => "abc\x00\x00\x00\x00\x00\x00\x00"

str2 = BinData::String.new(str1)  # <--- This is what you are attempting.
p str2.to_binary_s # => "abc"       <--- You are expecting the parameters to be copied.
```
In this simplified example, `str2` will *only* copy the raw value of `str1`. No parameters of `str1` are copied.

Not all file formats are able to be structured as simultaneously declarative and imperative.

You may or may not be able to re-design your file format to accomplish this.
