### ISSUE TITLE
DelayedIO ignores onlyif

### ISSUE THREAD

**Issue by zeroSteiner** [dmendel/bindata#140]
When using a delayed_io field, if `onlyif` is specified for it, then it'll crash while reading data because it doesn't know where to read from.

<details>

```
class RecordWithOptionalField < BinData::Record
  auto_call_delayed_io
  endian :little
  
  uint8  :comment_flag
  delayed_io :comment, read_abs_offset: 1, onlyif: -> { has_comment? } do
    string :comment, length: 20
  end
  def has_comment?
    comment_flag.nonzero?
  end
end

pp(RecordWithOptionalField.read("\x00" + "hello world".ljust(20)))
```

```
/home/smcintyre/.rvm/gems/ruby-3.0.4/gems/bindata-2.4.10/lib/bindata/delayed_io.rb:123:in `read_now!': read from where? (IOError)
	from /home/smcintyre/.rvm/gems/ruby-3.0.4/gems/bindata-2.4.10/lib/bindata/delayed_io.rb:179:in `each'
	from /home/smcintyre/.rvm/gems/ruby-3.0.4/gems/bindata-2.4.10/lib/bindata/delayed_io.rb:179:in `block in read'
	from /home/smcintyre/.rvm/gems/ruby-3.0.4/gems/bindata-2.4.10/lib/bindata/base.rb:149:in `read'
	from /home/smcintyre/.rvm/gems/ruby-3.0.4/gems/bindata-2.4.10/lib/bindata/delayed_io.rb:179:in `read'
	from /home/smcintyre/.rvm/gems/ruby-3.0.4/gems/bindata-2.4.10/lib/bindata/base.rb:21:in `read'
	from test_bad.rb:17:in `<main>'
```
</details>

If you specify it for the child field, it's ignored.

<details>

```
class RecordWithOptionalField < BinData::Record
  auto_call_delayed_io
  endian :little
  
  uint8  :comment_flag
  delayed_io :comment, read_abs_offset: 1 do
    string :comment, length: 20, onlyif: -> { has_comment? }
  end
  def has_comment?
    comment_flag.nonzero?
  end
end

pp(RecordWithOptionalField.read("\x00" + "hello world".ljust(20)))
```

```
{:comment_flag=>0, :comment=>"hello world         "}
</details>
```

Both of these examples are pretty contrived. The actual instance where this issue came up was a structure that includes an offsets to 4 optional fields into a buffer where each field is optional (offset = 0) and the fields can be in any order. I was trying to use this using delayed_io into a buffer, but couldn't seem to get it to work when the fields weren't present.

**Comment by dmendel** [comment]
Fixed and a new release has been made. Thanks for the report.

>If you specify it for the child field, it's ignored.

Only the first child field of a Record responds to `:onlyif`. If you wish to apply `:onlyif` to a nested field then you should wrap it in a struct.

```ruby
[...]
  delayed_io :comment, read_abs_offset: 1 do
    struct :my_struct do
      string :comment, length: 20, onlyif: -> { has_comment? }
      string :some_other_comment, length: 20
    end
  end
```

**Comment by zeroSteiner** [comment]
Thank you very much!

**Comment by zeroSteiner** [comment]
Actually, I went back to test this and I'm not sure it's behaving in the way I'd expect.

Per [Optional Fields](https://github.com/dmendel/bindata/wiki/Records#optional-fields):
> If the value of this parameter is false, then the field will be as if it didn't exist in the record.

<details>
<summary>With Delayed IO</summary>

```
require 'bindata'
require 'pp'

class RecordWithOptionalField < BinData::Record
  auto_call_delayed_io
  endian :little
  
  uint8  :comment_flag
  delayed_io :comment, read_abs_offset: 1, onlyif: -> { has_comment? }  do
    string length: 20
  end
  def has_comment?
    comment_flag.nonzero?
  end
end

pp(RecordWithOptionalField.read("\x00" + "hello world".ljust(20)))
```

Output shows that `comment` is included and it's the default value.

```
ruby ~/test_bad.rb
{:comment_flag=>0,
 :comment=>
  "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"}
```
</details>

<details>
<summary>Without DelayedIO</summary>

```
require 'bindata'
require 'pp'

class RecordWithOptionalField < BinData::Record
  auto_call_delayed_io
  endian :little
  
  uint8  :comment_flag
  string length: 20, onlyif: -> { has_comment? }
  def has_comment?
    comment_flag.nonzero?
  end
end

pp(RecordWithOptionalField.read("\x00" + "hello world".ljust(20)))
```

Output omits the `comment` field entirely.
```
ruby ~/test_bad.rb
{:comment_flag=>0}
```
</details>

**Comment by dmendel** [comment]
Fixed and a new release has been made. Thanks for the report.
