### ISSUE TITLE
bit field + buffer + array = false can't be coerced into Integer

### ISSUE THREAD

**Issue by ccoenen** [dmendel/bindata#90]
I have distilled this case from a small project I'm working on. I'm using `bindata 2.3.5` and `ruby 2.4.1`. It will fail Test 2 and Test 3.

> .../gems/bindata-2.3.5/lib/bindata/io.rb:336:in `|': false can't be coerced into Integer (TypeError)

```ruby
require 'bindata'

class Foo < BinData::Primitive
  bit1 :abc
  bit7 :bla

  def get; bla; end
  def set(v); self.bla = v; end
end

class FooArray < BinData::Record
  uint8 :payload_size
  buffer :data, length: :payload_size do
    array :a, type: :foo, read_until: :eof
  end
end

# result should be something like this
#=> {:payload_size=>16, :data=>[18, 51, 0, 0, 32, 54, 18, 51, 31, 57, 126, 49, 71, 14, 107, 3]}

too_short_works = FooArray.read("\x10\x123\x00\x00 \xB6\x123\x1F\xB9~\xB1\xC7\x8E\xEB")
puts "Test 1: #{too_short_works}"

exact_length_fails = FooArray.read("\x10\x123\x00\x00 \xB6\x123\x1F\xB9~\xB1\xC7\x8E\xEB\x83")
puts "Test 2: #{exact_length_fails}"

too_long_fails = FooArray.read("\x10\x123\x00\x00 \xB6\x123\x1F\xB9~\xB1\xC7\x8E\xEB\x83garbagepadding")
puts "Test 3: #{too_long_fails}"
```

<details><summary>Output including Stack Trace</summary>

```
user@dev:~/workspace/testcase$ ruby bug.rb
Test 1: {:payload_size=>16, :data=>[18, 51, 0, 0, 32, 54, 18, 51, 31, 57, 126, 49, 71, 14, 107]}
(...)/gems/bindata-2.3.5/lib/bindata/io.rb:336:in `|': false can't be coerced into Integer (TypeError)
        from (...)/gems/bindata-2.3.5/lib/bindata/io.rb:336:in `accumulate_big_endian_bits'
        from (...)/gems/bindata-2.3.5/lib/bindata/io.rb:321:in `read_big_endian_bits'
        from (...)/gems/bindata-2.3.5/lib/bindata/io.rb:299:in `readbits'
        from (eval):30:in `read_and_return_value'
        from (...)/gems/bindata-2.3.5/lib/bindata/base_primitive.rb:127:in `do_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/struct.rb:138:in `block in do_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/struct.rb:138:in `each'
        from (...)/gems/bindata-2.3.5/lib/bindata/struct.rb:138:in `do_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/primitive.rb:116:in `read_and_return_value'
        from (...)/gems/bindata-2.3.5/lib/bindata/base_primitive.rb:127:in `do_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/array.rb:316:in `block in do_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/array.rb:313:in `loop'
        from (...)/gems/bindata-2.3.5/lib/bindata/array.rb:313:in `do_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/buffer.rb:93:in `block in do_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/io.rb:252:in `block in with_buffer'
        from (...)/gems/bindata-2.3.5/lib/bindata/io.rb:62:in `with_buffer_common'
        from (...)/gems/bindata-2.3.5/lib/bindata/io.rb:251:in `with_buffer'
        from (...)/gems/bindata-2.3.5/lib/bindata/buffer.rb:92:in `do_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/struct.rb:138:in `block in do_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/struct.rb:138:in `each'
        from (...)/gems/bindata-2.3.5/lib/bindata/struct.rb:138:in `do_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/base.rb:147:in `block in read'
        from (...)/gems/bindata-2.3.5/lib/bindata/base.rb:254:in `start_read'
        from (...)/gems/bindata-2.3.5/lib/bindata/base.rb:145:in `read'
        from (...)/gems/bindata-2.3.5/lib/bindata/base.rb:21:in `read'
        from bug.rb:24:in `<main>'
```
</details>

I also re-ran the same code with only a tiny change in `Foo`-class: With uint8 instead of the two bit fields, everything is fine and works as expected (i.e. no `TypeError`).

**Comment by dmendel** [comment]
Thanks for the report and detailed test case. Fixed in BinData 2.4.0
